staging:
  deploy_to: "/aytomad/app/VOLUN/volun_backend"
  ssh_port: 22
  server: staging.volun_backend.madrid.es
  user: xxxxx
  full_app_name: volun_backend
  server_name: staging.volun_backend.madrid.es
  db_server: postgre.volun_backend.madrid.es
  stage: 'staging'
  server_name: 'rorapppre07A.munimadrid.es'
  server: 'rorapppre07A.munimadrid.es'
  user:   'deploy'

preproduction:
  deploy_to: "/aytomad/app/VOLUN/volun_backend"
  ssh_port: 22
  server1: xxx.xxx.xxx.xxx
  server2: xxx.xxx.xxx.xxx
  full_app_name: volun_backend
  db_server: xxx.xxx.xxx.xxx
  stage: 'preproduction'
  server_name: 'rorapppre07A.munimadrid.es'
  server: 'rorapppre07A.munimadrid.es'
  user:   'deploy'

production:
  deploy_to: "/aytomad/app/VOLUN/volun_backend"
  ssh_port: 22
  server: xxx.xxx.xxx.xxx
  user: xxxxx
  full_app_name: volun_backend
  stage: 'production'
  server_name: 'rorapppre07A.munimadrid.es'
  server: 'rorapppre07A.munimadrid.es'
  user:   'deploy'
