staging:
  deploy_to: "/aytomad/app/volun/volun_backend"
  ssh_port: 22
  full_app_name: volun_backend
  stage: 'staging'
  server_name: 'rorapppre07A.munimadrid.es'
  server: 'rorapppre07A.munimadrid.es'
  user:   'deploy'

preproduction:
  deploy_to: "/aytomad/app/volun/volun_backend"
  ssh_port: 22
  full_app_name: volun_backend
  stage: 'preproduction'
  server_name: 'rorapppre07A.munimadrid.es'
  server: 'rorapppre07A.munimadrid.es'
  user:   'deploy'

production:
  deploy_to: "/aytomad/app/volun/volun_backend"
  ssh_port: 22
  full_app_name: volun_backend
  stage: 'production'
  server_name: 'rorapppro07A.munimadrid.es'
  server: 'rorapppro07A.munimadrid.es'
  user:   'deploy'
